from setuptools import setup, find_packages


with open("README.rst") as f:
    long_description = f.read()

setup(
    dependency_links=[
        "git+https://github.com/stellar/django-polaris.git@2b59d228172a47ec4194435e04d127071da2fa9b#egg=django-polaris"
    ],
    name="django-polaris-circle",
    version="0.1.0",
    description="A circle-based custody implementation for django-polaris",
    long_description=long_description,
    long_description_content_type="text/x-rst",
    author="Jake Urban",
    author_email="jake@stellar.org",
    license="Apache license 2.0",
    classifiers=[
        "Environment :: Web Environment",
        "Framework :: Django",
        "Framework :: Django :: 3.2",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.7",
    ],
    keywords=["stellar", "sdf", "anchor", "polaris", "circle", "usdc", "custody"],
    include_package_data=True,
    packages=find_packages(),
    install_requires=[
        "aiohttp==3.7.4.post0",
        "aiohttp-sse-client==0.2.1",
        "asgiref==3.4.1",
        "async-timeout==3.0.1; python_full_version >= '3.5.3'",
        "attrs==21.2.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
        "certifi==2021.5.30",
        "cffi==1.14.6",
        "chardet==4.0.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
        "charset-normalizer==2.0.4; python_version >= '3'",
        "cryptography==3.4.8",
        "django==3.2.7",
        "django-cors-headers==3.8.0",
        "django-environ==0.6.0",
        "django-model-utils==4.1.1",
        "djangorestframework==3.12.4",
        "idna==3.2; python_version >= '3'",
        "mnemonic==0.20",
        "multidict==5.1.0; python_version >= '3.6'",
        "pycparser==2.20; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "pyjwt==2.1.0",
        "pynacl==1.4.0",
        "pytz==2021.1",
        "requests==2.26.0",
        "six==1.16.0; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
        "sqlparse==0.4.1",
        "stellar-base-sseclient==0.0.21",
        "stellar-sdk==4.1.1",
        "toml==0.10.2",
        "typing-extensions==3.10.0.0; python_version < '3.8'",
        "urllib3==1.26.6; python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4' and python_version < '4'",
        "whitenoise==5.3.0",
        "yarl==1.6.3; python_version >= '3.6'",
    ],
    python_requires=">=3.7",
)
